#ores
ore:
  diamond_ore: 5
  emerald_ore: 10
  lapis_ore: 2
  redstone_ore: 2
  iron_ore: 1
  coal_ore: 1
  gold_ore: 3 #includes nether gold ore
  ancient_debris: 10
  quartz_ore: 1
  copper_ore: 1
  amethyst:
    block: 2
    buds:
      small: 1
      medium: 1
      large: 2
      cluster: 3
      shard: 1

#crops
crop:
  wheat:
    stage0: 0
    stage1: 0
    stage2: 0
    stage3: 0
    stage4: 0
    stage5: 1
    stage6: 1
    stage7: 2
  potatoes:
    stage0: 0
    stage1: 0
    stage2: 0
    stage3: 0
    stage4: 1
    stage5: 1
    stage6: 2
    stage7: 3
  carrots:
    stage0: 0
    stage1: 0
    stage2: 0
    stage3: 0
    stage4: 1
    stage5: 1
    stage6: 2
    stage7: 3
  beetroot:
    stage0: 0
    stage1: 0
    stage2: 0
    stage3: 1
  cocoa:
    stage0: 0
    stage1: 0
    stage2: 2
  pumpkin: 3
  melon: 3
  sweet_berry_bush:
    stage0: 0
    stage1: 0
    stage2: 1

#entities
entity:
#1.0 Mobs
  baby_zombie: 2
  blaze: 1
  cave_spider: 1
  chicken: 1
  cow: 1
  creeper: 1
  ender_dragon: 10
  enderman: 2
  ghast: 1
  magma_cube: 1
  mushroom_cow: 1
  pig: 1
  sheep: 1
  silverfish: 1
  skeleton: 1
  slime: 1
  snowman: 0
  spider: 1
  squid: 0
  villager: 1
  wolf: 1
  zombie: 1

#1.2 Mobs
  cat: 0
  iron_golem: 1
  ocelot: 1

#1.4 Mobs
  bat: 0
  witch: 2
  wither: 10
  wither_skeleton: 2
  zombie_villager: 1

#1.6 Mobs
  donkey: 1
  horse: 1
  mule: 1
  skeleton_horse: 0
  zombie_horse: 0

#1.8 Mobs
  elder_guardian: 3
  endermite: 1
  guardian: 2
  rabbit: 1

#1.9 Mobs
  shulker: 2

#1.10 Mobs
  baby_polar_bear: 1
  husk: 1
  polar_bear: 1
  stray: 1

#1.11 Mobs
  evoker: 3
  llama: 1
  vex: 3
  vindicator: 1

#1.12 Mobs
  illusioner: 0
  parrot: 0

#1.13 Mobs
  cod: 0
  dolphin: 1
  drowned: 1
  phantom: 1
  pufferfish: 1
  salmon: 0
  tropical_fish: 0
  turtle: 1

#1.14 Mobs
  fox: 1
  panda: 1
  pillager: 1
  ravager: 2
  trader_llama: 1
  wandering_trader: 1

#1.15 Mobs
  bee: 1

#1.16 Mobs
  baby_piglin: 1
  hoglin: 2
  piglin: 1
  strider: 1
  zoglin: 2
  zombified_piglin: 2

#1.16.2 Mobs
  piglin_brute: 2

#1.17 Mobs
  axolotl: 1
  glow_squid: 1
  goat: 1

#1.19 Mobs
  allay: 0
  frog: 0
  tadpole: 0
  warden: 15

#1.20 Mobs
  camel: 0
  sniffer: 0

#1.20.5 Mobs
  armadillo: 0

#Ignored mobs
  giant: 0
  armor_stand: 0

fishing: 2

#Message that is sent to the player whenever they pay somebody who is offline.
offlinepaymessage: Don't forget to inform that player that you have paid them.

use-memail: true
