name: MeConomy
version: '${project.version}'
main: not.mepipe.meconomy.Main
api-version: 1.16
authors: [ MePipe ]
description: Adds a customizable currency system.
depend: [ Vault ]
softdepend: [ MeMail ]

commands:
  pay:
    description: Pay somebody
  currency:
    description: Manage somebody's currency or the plugin config